# Generated by Django 3.2.7 on 2021-10-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor_select',
            field=models.TextField(default='Vivek'),
        ),
    ]
