# Generated by Django 3.2.7 on 2021-10-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_patient_doctor_select'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=25)),
                ('hos_name', models.CharField(max_length=50)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('paid_cost', models.IntegerField(default=0)),
            ],
        ),
    ]
