# Generated by Django 3.2.7 on 2021-10-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='paid_cost',
            field=models.BooleanField(default=False),
        ),
    ]
